# Generated by Django 3.1.4 on 2021-01-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210111_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setmodels',
            name='setID',
            field=models.CharField(default='4SS0A8WBOQVF6J3DHRUJ', max_length=20),
        ),
    ]
