# Generated by Django 3.1.4 on 2021-01-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210112_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setmodels',
            name='setEnd',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='setmodels',
            name='setID',
            field=models.CharField(default='6Y89VEHWIRF6I75ENEYX', max_length=20),
        ),
        migrations.AlterField(
            model_name='setmodels',
            name='setStart',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='setmodels',
            name='setUT',
            field=models.DateTimeField(),
        ),
    ]
