# Generated by Django 3.1.4 on 2021-01-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210115_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setmodels',
            name='setDatumeLock',
        ),
        migrations.AddField(
            model_name='setmodels',
            name='setDateLock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='setmodels',
            name='setID',
            field=models.CharField(default='VBZ89OKJQI4EQVU7UCRV', max_length=20),
        ),
    ]
