# Generated by Django 3.1.4 on 2021-01-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210115_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='setmodels',
            name='setTest',
            field=models.JSONField(blank=True, default=dict, max_length=500000),
        ),
        migrations.AlterField(
            model_name='setmodels',
            name='setID',
            field=models.CharField(default='8SV71WFJQTO8TOUCIP4Q', max_length=20),
        ),
    ]
