# Generated by Django 3.1.4 on 2021-02-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210125_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setmodels',
            name='setID',
            field=models.CharField(default='Z999KNCEX13DEPPD0X3Q', max_length=20),
        ),
    ]
