# Generated by Django 3.1.4 on 2020-12-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setmodels',
            name='setCity',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='setmodels',
            name='setCityUp',
            field=models.CharField(default='', max_length=50),
        ),
    ]
