# Generated by Django 3.1.4 on 2021-01-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setmodels',
            name='setCity',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='setmodels',
            name='setCityUp',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='setmodels',
            name='setCurrentProgress',
            field=models.JSONField(blank=True, default='{}', max_length=500000),
        ),
        migrations.AddField(
            model_name='setmodels',
            name='setDelinquents',
            field=models.JSONField(blank=True, default='{}', max_length=500000),
        ),
        migrations.AddField(
            model_name='setmodels',
            name='setEnd',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='setmodels',
            name='setID',
            field=models.CharField(default='4UFER1Y1UY39J32XE6Y4', max_length=20),
        ),
        migrations.AddField(
            model_name='setmodels',
            name='setProgressLimit',
            field=models.JSONField(blank=True, default='{}', max_length=500000),
        ),
        migrations.AddField(
            model_name='setmodels',
            name='setReady',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='setmodels',
            name='setRepPts',
            field=models.JSONField(blank=True, default='{}', max_length=500000),
        ),
        migrations.AddField(
            model_name='setmodels',
            name='setRepitations',
            field=models.CharField(choices=[('WKLY', 'Weekly'), ('MTHY', 'Monthly')], default='MTHY', max_length=4),
        ),
        migrations.AddField(
            model_name='setmodels',
            name='setStart',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='setmodels',
            name='setTimeLimit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='setmodels',
            name='setUT',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='setmodels',
            name='setUsers',
            field=models.JSONField(blank=True, default='{}', max_length=500000),
        ),
        migrations.AlterField(
            model_name='setmodels',
            name='setAmt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='setmodels',
            name='setPeopleLimit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='setmodels',
            name='setTime',
            field=models.IntegerField(default=0),
        ),
    ]
