# Generated by Django 3.1.4 on 2021-01-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210111_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='setmodels',
            name='setDateLock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='setmodels',
            name='setEnd',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='setmodels',
            name='setID',
            field=models.CharField(default='Q0ZNX295A3WAI70UZCZS', max_length=20),
        ),
        migrations.AlterField(
            model_name='setmodels',
            name='setStart',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='setmodels',
            name='setUT',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
