# Generated by Django 3.1.4 on 2020-12-30 19:10

# import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201230_1338'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='setmodels',
    #         name='setUsers',
    #         field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None),
    #     ),
    # ]
