# Generated by Django 3.1.4 on 2020-12-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201230_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setmodels',
            name='setUsers',
            field=models.JSONField(blank=True, default='', max_length=500000),
        ),
    ]
