# Generated by Django 3.1.4 on 2020-12-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201230_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='setmodels',
            name='setID',
            field=models.CharField(default='DYNURMLG93S7MKHQPWVI', max_length=20),
        ),
    ]
