# Generated by Django 3.1.4 on 2020-12-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SetModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setAmt', models.IntegerField(blank=True, default=0, null=True)),
                ('setTime', models.IntegerField(blank=True, default=0, null=True)),
                ('setPeopleLimit', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
