# Generated by Django 3.1.4 on 2021-01-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_setmodels_setid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setmodels',
            name='setID',
            field=models.CharField(default='GSZO99GM770AQ5G0OFZ1', max_length=20),
        ),
        migrations.AlterField(
            model_name='setmodels',
            name='setUsers',
            field=models.JSONField(blank=True, default='{[]}', max_length=500000),
        ),
    ]
