# Generated by Django 3.1.4 on 2021-01-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210102_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setmodels',
            name='setAmt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='setmodels',
            name='setCity',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='setmodels',
            name='setCityUp',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='setmodels',
            name='setID',
            field=models.CharField(default='MAGMETKVHO4G1HZG7BLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='setmodels',
            name='setPeopleLimit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='setmodels',
            name='setTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='setmodels',
            name='setUsers',
            field=models.JSONField(blank=True, default='{}', max_length=500000),
        ),
    ]
