# Generated by Django 3.1.4 on 2021-01-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210111_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setmodels',
            name='setID',
            field=models.CharField(default='B42P3ME9FNIWP709Y1HF', max_length=20),
        ),
    ]
