# Generated by Django 3.1.4 on 2021-01-11 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    # dependencies = [
    #     ('main', '0012_auto_20210111_1635'),
    # ]

    operations = [
        migrations.AlterField(
            model_name='setmodels',
            name='setEnd',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='setmodels',
            name='setID',
            field=models.CharField(default='ZEIN5MY1JOVDXUDJZOGO', max_length=20),
        ),
        migrations.AlterField(
            model_name='setmodels',
            name='setStart',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='setmodels',
            name='setUT',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
