# Generated by Django 3.1.4 on 2021-01-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210111_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setmodels',
            name='setEnd',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='setmodels',
            name='setID',
            field=models.CharField(default='MXIXYMEIWOMEA6SZ1UZ4', max_length=20),
        ),
        migrations.AlterField(
            model_name='setmodels',
            name='setStart',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='setmodels',
            name='setUT',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
