# Generated by Django 3.1.4 on 2021-01-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210111_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setmodels',
            name='setID',
            field=models.CharField(default='AUDPB5YTK7TW3EN8FJQH', max_length=20),
        ),
    ]
